on:
  push:
    branches:
      - 'master'

permissions:
  contents: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  fe-build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🔄 Checkout Code
        uses: actions/checkout@v4
      - name: 📦 Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: 🔧 Install node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: 📁 Install node_modules
        run: pnpm install
      - name: ️🏗️ Build application
        run: pnpm build
      - name: 🚀 Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
